[phases.setup]
nixPkgs = ["nodejs-20_x", "caddy"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmd = "caddy file-server --listen :3000 --root /app/dist"
